export const products = [
  {
    id: '73805165',
    name: '25 Stem Rose Bouquet',
    price: 85,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/73805165.png',
    tag: 'Classic roses',
    description: 'A hand-tied bouquet of 25 roses, starting at $85.',
  },
  {
    id: '90317873',
    name: '50 Stem Rose Bouquet',
    price: 155,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/90317873.png',
    tag: 'Statement roses',
    description: 'A fuller rose bouquet of 50 stems, starting at $155.',
  },
  {
    id: '90318014',
    name: '75 Stem Rose Bouquet',
    price: 225,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/90318014.png',
    tag: 'Grand gesture',
    description: 'A lavish bouquet of 75 roses, starting at $225.',
  },
  {
    id: '90318236',
    name: '100 Stem Rose Bouquet',
    price: 300,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/90318236.png',
    tag: 'Showstopper',
    description: 'One hundred roses, arranged by hand, starting at $300.',
  },
  {
    id: '90318369',
    name: '100+ Stem Rose Bouquet',
    price: 385,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/90318369.png',
    tag: 'Custom size',
    description: 'Contact us beforehand for a quote on rose bouquets larger than 100 stems.',
  },
  {
    id: '93485254',
    name: 'Standing Heart Arrangement',
    price: 145,
    priceFrom: true,
    category: 'Rose Bouquets',
    image: '/images/products/placeholder.jpg',
    tag: 'Statement piece',
    description: 'A standing heart arrangement of roses, starting at $145.',
  },
  {
    id: '90319601',
    name: 'Mixed Blooms Bouquet',
    price: 50,
    priceFrom: true,
    category: 'Mixed Floral Bouquets',
    image: '/images/products/90319601.png',
    tag: 'Seasonal mix',
    description: 'A mixed floral bouquet of seasonal blooms, starting at $50.',
  },
  {
    id: '94374895',
    name: 'Customized Bottle',
    price: 120,
    priceFrom: true,
    category: 'Other Services',
    image: '/images/products/94374895.png',
    tag: 'Gift add-on',
    description: 'Full bottle price serves as deposit.',
  },
  {
    id: '94374999',
    name: 'Bouquet & Bottle Bundle',
    price: 205,
    priceFrom: true,
    category: 'Other Services',
    image: '/images/products/94374999.png',
    tag: 'Bundle',
    description: 'For this service, 60% of the bouquet price and full bottle price serves as deposit total.',
  },
  {
    id: '90319687',
    name: 'Money Bouquet',
    price: 0,
    contactOnly: true,
    category: 'Other Services',
    image: '/images/products/placeholder.jpg',
    tag: 'Custom order',
    description: 'This service requires full payment upfront. Priced at $2.50 per bill — contact us to order.',
  },
  {
    id: '93485280',
    name: 'Wedding Bouquet & Event Arrangements',
    price: 0,
    contactOnly: true,
    category: 'Event Arrangements',
    image: '/images/products/placeholder.jpg',
    tag: 'Quote required',
    description: 'Message us for a quote before booking this service.',
  },
];

export const stories = [
  {slug:'make-your-flowers-last',title:'A little care, a little longer.',category:'FLOWER CARE',image:'/images/bouquet-2.jpg',intro:'Simple rituals to keep your flowers happy, day after day.',body:['Start with a clean vase and fresh, room-temperature water. Remove any leaves that will sit below the waterline.','Trim the stems at an angle with clean, sharp scissors, then place them in water straight away. Use the flower food supplied with your arrangement according to its instructions.','Keep your flowers away from direct sunlight, heating vents, and ripening fruit. Refresh the water every two days and give the stems another small trim.','Remove faded flowers as you go. Every stem has its own rhythm, and a little attention makes the whole arrangement last longer.']},
  {slug:'the-beauty-of-seasonal-flowers',title:'Let the season choose.',category:'FROM THE STUDIO',image:'/images/bouquet-3.jpg',intro:'Why our favorite arrangements begin with what’s growing now.',body:['Seasonal flowers bring a sense of place and time to an arrangement. They remind us to notice what is happening just outside our door.','In spring, we love the movement of tulips and ranunculus. Summer brings abundant garden roses and dahlias, while autumn invites richer colors and textural foliage.','A designer’s choice bouquet is an invitation to work with the most beautiful stems available that week. Your flowers may look a little different each time—that is part of their charm.']}
];
